name: we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH connection to Bastion Host
        run: |
          echo "${{ secrets.BASTION_HOST_KEY }}" > bastion_key.pem
          chmod 600 bastion_key.pem
          eval "$(ssh-agent -s)"
          ssh-add bastion_key.pem
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Connect to WAS through Bastion Host and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -J ${{ secrets.BASTION_HOST_USERNAME }}@${{ secrets.BASTION_HOST_IP }} -i bastion_key.pem ubuntu@10.0.1.4 << 'EOF'
            cd /home/ubuntu/server/Spring_ci-cd
            git pull origin main

            # Navigate to build directory and restart application
            cd build/libs
            sudo fuser -k -n tcp 8080
            chmod +x ./cicd_test-0.0.1-SNAPSHOT.jar
            nohup java -jar cicd_test-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
          EOF
