name: we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to WAS via Bastion
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST_IP }}           # bastion host IP
          username: ${{ secrets.BASTION_HOST_USERNAME }} # bastion host user (예: ubuntu)
          key: ${{ secrets.BASTION_HOST_KEY }}           # bastion host SSH Key
          script: |
            # 1) bastion 호스트 내 pem 파일 권한 설정 (권장)
            chmod 400 /home/ubuntu/keys/we_gift_ec2_key.pem

            # 2) bastion → WAS 서버(10.0.1.4) SSH 접속 후 여러 명령 수행
            ssh -o StrictHostKeyChecking=no \
                -i /home/ubuntu/keys/we_gift_ec2_key.pem \
                ubuntu@10.0.1.4 \
            "  
              echo '현재 서버 위치:' \$(pwd)

              # 실제 존재하는 디렉터리로 이동
              cd /home/ubuntu/server/Spring_ci-cd

              echo 'Git Pull 시작'
              git pull origin main
            
              # 빌드 실행
              ./gradlew clean build
              
              # 빌드 산출물 위치로 이동
              cd /home/ubuntu/server/Spring_ci-cd/build/libs

              echo '8080 포트 사용 프로세스 종료'
              sudo fuser -k -n tcp 8080

              echo 'JAR 실행권한 부여'
              chmod +x ./*SNAPSHOT.jar

              echo '새로운 JAR 구동'
              nohup java -jar ./*SNAPSHOT.jar > ./output.log 2>&1 &

              echo '배포 완료'
            "
