name: we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: WAS host connection though bastion host and pull from git-hub + restart WAS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST_IP }}
          username: ${{ secrets.BASTION_HOST_USERNAME }}
          key: ${{ secrets.BASTION_HOST_KEY }}
          script: |
            cd /home/ubuntu/keys
            pwd
            ssh -i we_gift_ec2_key.pem ubuntu@10.0.1.4
            
            [ -d "/home/ubuntu" ] && echo "디렉토리가 존재합니다." || echo "디렉토리가 존재하지 않습니다."
            cd server/Spring_ci-cd
            git pull origin main
            cd /home/ubuntu/server/Spring_ci-cd/build/libs
            sudo fuser -k -n tcp 8080
            chmod +x ./cicd_test-0.0.1-SNAPSHOT.jar
            nohup java -jar *SNAPSHOT.jar > ./output.log 2>&1 &
