name: we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: WAS host connection though bastion host
        run: |
          ssh -i ${{ secrets.BASTION_HOST_KEY }} ${{ secrets.BASTION_HOST_USERNAME }}@${{ secrets.BASTION_HOST_IP }}
          cd /home/ubuntu/keys
          pwd
          ssh -i we_gift_ec2_key.pem ubuntu@10.0.1.4

      - name: pull from git-hub and restart WAS
        run: |
          cd ~
          cd /home
          pwd
          ls -al
          cd server/Spring_ci-cd
          git pull origin main
          cd /home/ubuntu/server/Spring_ci-cd/build/libs
          sudo fuser -k -n tcp 8080
          chmod +x ./cicd_test-0.0.1-SNAPSHOT.jar
          nohup java -jar *SNAPSHOT.jar > ./output.log 2>&1 &