name: we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.WE_GIFT_EC2_KEY }}" > /home/ubuntu/keys/we_gift_ec2_key.pem
          chmod 600 /home/ubuntu/keys/we_gift_ec2_key.pem

      - name: WAS host connection through bastion host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST_IP }}
          username: ${{ secrets.BASTION_HOST_USERNAME }}
          key: ${{ secrets.BASTION_HOST_KEY }}
          script_stop: true
          script: |
            ssh -o ProxyCommand="ssh -i /home/ubuntu/keys/we_gift_ec2_key.pem -W %h:%p ubuntu@${{secrets.BASTION_HOST_IP}}" \
                -i /home/ubuntu/keys/we_gift_ec2_key.pem ubuntu@10.0.1.4 << 'EOF'
            git -C /home/ubuntu/server/Spring_ci-cd pull origin main
            PID=$(lsof -ti:8080)
            if [ -n "$PID" ]; then
              kill -15 $PID
              sleep 5
            fi
            nohup java -jar /home/ubuntu/server/Spring_ci-cd/build/libs/*SNAPSHOT.jar > /home/ubuntu/server/Spring_ci-cd/output.log 2>&1 &
            EOF