name: we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      # 예: main 브랜치에 push되면 실행
      - name: Deploy to WAS via Bastion
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST_IP }}                  # 배스천 호스트 IP
          username: ${{ secrets.BASTION_HOST_USERNAME }}        # 배스천 호스트 Username (ex: ubuntu)
          key: ${{ secrets.BASTION_HOST_KEY }}                  # 배스천 호스트 SSH Key
          script: |
            # 필요한 경우 퍼미션 설정 (권장)
            chmod 400 /home/ubuntu/keys/we_gift_ec2_key.pem

            # 배스천 호스트에서 프라이빗 IP(10.0.1.4)로 SSH 접속
            ssh -o StrictHostKeyChecking=no \
                -i /home/ubuntu/keys/we_gift_ec2_key.pem \
                ubuntu@10.0.1.4 << 'ENDSSH'
            
              # -----------------------------
              # 여기가 WAS 서버 내부에서 실행될 명령어들
              # -----------------------------
              echo "현재 서버 위치: $(pwd)"
              cd /home/ubuntu/server/Spring_ci-cd
            
              echo "Git Pull 시작"
              git pull origin main
            
              # 빌드 산출물 디렉토리로 이동
              cd /home/ubuntu/server/Spring_ci-cd/build/libs

              echo "8080 포트 사용 프로세스 종료"
              sudo fuser -k -n tcp 8080

              echo "JAR 실행권한 부여"
              chmod +x ./cicd_test-0.0.1-SNAPSHOT.jar
            
              echo "새로운 JAR 구동"
              nohup java -jar cicd_test-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &

              echo "배포 완료"
              ENDSSH
