name: we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to WAS via Bastion
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST_IP }}
          username: ${{ secrets.BASTION_HOST_USERNAME }}
          key: ${{ secrets.BASTION_HOST_KEY }}
          script: |
            # 1) bastion 호스트 내 pem 파일 권한 설정
            chmod 400 /home/ubuntu/keys/we_gift_ec2_key.pem

            # 2) bastion → WAS 서버 SSH
            ssh -o StrictHostKeyChecking=no \
                -i /home/ubuntu/keys/we_gift_ec2_key.pem \
                ubuntu@10.0.1.4 << 'EOS'
            
            echo '[서버] 현재 위치:' $(pwd)
            
            cd /home/ubuntu/server/Spring_ci-cd
            echo '[서버] Git Pull 시작'
            git pull origin main

            echo '[서버] application.yml 덮어씌우기'
            cat <<EOT > /home/ubuntu/server/Spring_ci-cd/src/main/resources/application.yml
  ${{ secrets.WAS_YML }}
  EOT
  
  echo '[서버] 빌드 실행'
  ./gradlew clean build
  
  cd /home/ubuntu/server/Spring_ci-cd/build/libs
  echo '[서버] 8080 포트 사용 프로세스 종료'
  sudo fuser -k -n tcp 8080
  
  echo '[서버] JAR 실행권한 부여'
  chmod +x ./*SNAPSHOT.jar
  
  echo '[서버] 새로운 JAR 구동'
  nohup java -jar ./*SNAPSHOT.jar > ./output.log 2>&1 &
  
  echo '[서버] 배포 완료'
  
  EOS
