name : we_gift_was deploy process

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: WAS host connection though bastion host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.BASTION_HOST_IP}}
          username: ${{secrets.BASTION_HOST_USERNAME}}
          key: ${{secrets.BASTION_HOST_KEY}}
          script_stop: true
          script: |
            cd /home/ubuntu/keys
            ssh -i we_gift_ec2_key.pem ubuntu@10.0.1.4